# Kitty example for Berka Mono Instrument
font_family      family="Berka Mono Instrument"
bold_font        family="Berka Mono Instrument" style="Bold"
italic_font      family="Berka Mono Instrument" style="Italic"
bold_italic_font family="Berka Mono Instrument" style="Bold Italic"
font_size        15.0

# Programming ligatures
disable_ligatures never

# Closer variant:
# font_family      family="Berka Mono Closer"
# bold_font        family="Berka Mono Closer" style="Bold"
# italic_font      family="Berka Mono Closer" style="Italic"
# bold_italic_font family="Berka Mono Closer" style="Bold Italic"

# Focus variant:
# font_family      family="Berka Mono Focus"
# bold_font        family="Berka Mono Focus" style="Bold"
# italic_font      family="Berka Mono Focus" style="Italic"
# bold_italic_font family="Berka Mono Focus" style="Bold Italic"
