# Kitty example for Berka Mono Closer
font_family      family="Berka Mono Closer"
bold_font        family="Berka Mono Closer" style="Bold"
italic_font      family="Berka Mono Closer" style="Italic"
bold_italic_font family="Berka Mono Closer" style="Bold Italic"
font_size        15.0

# Programming ligatures
disable_ligatures never

# SemiCondensed variant:
# font_family      family="Berka Mono Closer SemiCondensed"
# bold_font        family="Berka Mono Closer SemiCondensed" style="Bold"
# italic_font      family="Berka Mono Closer SemiCondensed" style="Italic"
# bold_italic_font family="Berka Mono Closer SemiCondensed" style="Bold Italic"

# Narrow variant:
# font_family      family="Berka Mono Closer Narrow"
# bold_font        family="Berka Mono Closer Narrow" style="Bold"
# italic_font      family="Berka Mono Closer Narrow" style="Italic"
# bold_italic_font family="Berka Mono Closer Narrow" style="Bold Italic"

# Control variant:
# font_family      family="Berka Mono Control"
# bold_font        family="Berka Mono Control" style="Bold"
# italic_font      family="Berka Mono Control" style="Italic"
# bold_italic_font family="Berka Mono Control" style="Bold Italic"
